### Word2Vec

In [1]:
import pandas as pd
data=pd.read_csv('all_kindle_review.csv')
data.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [2]:
df=data[['reviewText','rating']]
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

### Preprocessing and Cleaning

In [3]:
df['rating']=df['rating'].apply(lambda x:0 if x<3 else 1)

In [4]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [5]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [6]:
import re
from bs4 import BeautifulSoup
from nltk.corpus import stopwords

# Load stopwords ONCE
stop_words = set(stopwords.words('english'))

corpus = []

for review in df['reviewText']:

    # Convert to string
    review = str(review)

    # Remove URLs
    review = re.sub(
        r'https?://\S+|www\.\S+',
        '',
        review
    )

    # Remove HTML tags
    review = BeautifulSoup(review, 'html.parser').get_text()

    # Remove special characters
    review = re.sub('[^a-zA-Z0-9-]+', ' ', review)

    # Lowercase
    review = review.lower()

    # Remove stopwords
    words = [
        word for word in review.split()
        if word not in stop_words
    ]

    # Lemmatization
    words = [
        lemmatizer.lemmatize(word)
        for word in words
    ]

    # Join
    review = ' '.join(words)

    # Remove extra spaces
    review = ' '.join(review.split())

    corpus.append(review)

In [7]:
df['reviewText']=corpus

In [8]:
df.head()

                                          reviewText  rating
0  jace rankin may short nothing mess man hauled ...       1
1  great short read want put read one sitting sex...       1
2  start saying first four book expecting conclud...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [9]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [10]:
# Converts the reviewText into tokenized sentences, so that it can be given to Word2Vec
words = []

for paragraph in df['reviewText']:
    sent_token = sent_tokenize(paragraph)

    for sentence in sent_token:
        words.append(simple_preprocess(sentence))

In [11]:
# Training word2vec from scratch
import gensim
model=gensim.models.Word2Vec(words)

In [12]:
model.wv.index_to_key

['book',
 'story',
 'read',
 'one',
 'character',
 'like',
 'good',
 'would',
 'love',
 'really',
 'time',
 'get',
 'author',
 'series',
 'well',
 'reading',
 'much',
 'first',
 'even',
 'short',
 'way',
 'great',
 'could',
 'know',
 'sex',
 'make',
 'little',
 'two',
 'thing',
 'want',
 'plot',
 'think',
 'romance',
 'also',
 'find',
 'end',
 'life',
 'see',
 'scene',
 'go',
 'enjoyed',
 'never',
 'written',
 'woman',
 'take',
 'kindle',
 'many',
 'lot',
 'year',
 'work',
 'say',
 'thought',
 'interesting',
 'bit',
 'going',
 'found',
 'novel',
 'writing',
 'give',
 'another',
 'liked',
 'loved',
 'better',
 'man',
 'hot',
 'got',
 'feel',
 'come',
 'still',
 'star',
 'review',
 'though',
 'back',
 'enough',
 'reader',
 'people',
 'friend',
 'made',
 'something',
 'page',
 'part',
 'world',
 'bad',
 'free',
 'need',
 'keep',
 'new',
 'relationship',
 'enjoy',
 'together',
 'next',
 'recommend',
 'start',
 'felt',
 'best',
 'word',
 'put',
 'guy',
 'main',
 'however',
 'looking',
 'day',
 'long',
 'line',
 'fun',
 'since',
 'hard',
 'right',
 'real',
 'point',
 'ending',
 'family',
 'sure',
 'different',
 'without',
 'nothing',
 'wanted',
 'hero',
 'ever',
 'every',
 'action',
 'anything',
 'old',
 'always',
 'men',
 'definitely',
 'heroine',
 'look',
 'help',
 'worth',
 'actually',
 'three',
 'let',
 'place',
 'fact',
 'pretty',
 'problem',
 'around',
 'left',
 'quite',
 'feeling',
 'whole',
 'idea',
 'second',
 'away',
 'sexy',
 'vampire',
 'brother',
 'seemed',
 'nice',
 'try',
 'tell',
 'mystery',
 'might',
 'kind',
 'someone',
 'getting',
 'done',
 'chapter',
 'novella',
 'far',
 'started',
 'issue',
 'may',
 'almost',
 'turn',
 'yet',
 'tale',
 'set',
 'girl',
 'couple',
 'mind',
 'maybe',
 'seems',
 'kept',
 'reason',
 'everything',
 'past',
 'last',
 'quick',
 'full',
 'beginning',
 'said',
 'writer',
 'wish',
 'finish',
 'trying',
 'mate',
 'fantasy',
 'night',
 'strong',
 'description',
 'hope',
 'others',
 'father',
 'job',
 'must',
 'believe',
 'development',
 'meet',
 'least',
 'human',
 'erotic',
 'sweet',
 'fast',
 'anyone',
 'although',
 'fan',
 'happy',
 'home',
 'mean',
 'care',
 'easy',
 'overall',
 'especially',
 'able',
 'money',
 'big',
 'child',
 'buy',
 'understand',
 'person',
 'young',
 'show',
 'forward',
 'disappointed',
 'detail',
 'storyline',
 'sexual',
 'heart',
 'style',
 'used',
 'went',
 'probably',
 'high',
 'took',
 'sense',
 'wait',
 'true',
 'seem',
 'gave',
 'write',
 'favorite',
 'interest',
 'instead',
 'else',
 'type',
 'wrong',
 'case',
 'rather',
 'along',
 'less',
 'price',
 'use',
 'longer',
 'rest',
 'male',
 'wonderful',
 'several',
 'given',
 'lost',
 'ok',
 'change',
 'told',
 'twist',
 'female',
 'side',
 'either',
 'cover',
 'came',
 'half',
 'fall',
 'developed',
 'error',
 'finally',
 'stop',
 'knew',
 'later',
 'perfect',
 'alpha',
 'husband',
 'enjoyable',
 'completely',
 'light',
 'name',
 'course',
 'glad',
 'lead',
 'happened',
 'future',
 'order',
 'making',
 'fiction',
 'wolf',
 'happens',
 'quickly',
 'okay',
 'everyone',
 'wife',
 'amazon',
 'boring',
 'eye',
 'interested',
 'waste',
 'situation',
 'happen',
 'yes',
 'attention',
 'believable',
 'lover',
 'premise',
 'already',
 'bought',
 'needed',
 'finished',
 'sister',
 'steamy',
 'length',
 'become',
 'highly',
 'boy',
 'mother',
 'follow',
 'town',
 'chance',
 'moment',
 'entire',
 'funny',
 'truly',
 'title',
 'genre',
 'school',
 'werewolf',
 'sometimes',
 'dialogue',
 'ended',
 'head',
 'guess',
 'dark',
 'thinking',
 'paranormal',
 'sorry',
 'call',
 'hand',
 'move',
 'live',
 'leave',
 'editing',
 'entertaining',
 'stand',
 'oh',
 'run',
 'totally',
 'house',
 'version',
 'sort',
 'romantic',
 'age',
 'war',
 'self',
 'pick',
 'lack',
 'coming',
 'spoiler',
 'depth',
 'language',
 'erotica',
 'deal',
 'alone',
 'add',
 'experience',
 'unfortunately',
 'secret',
 'ago',
 'reviewer',
 'soon',
 'month',
 'turned',
 'usually',
 'pack',
 'expected',
 'begin',
 'dream',
 'potential',
 'matter',
 'expect',
 'giving',
 'opinion',
 'save',
 'throughout',
 'rating',
 'hour',
 'gay',
 'adult',
 'figure',
 'death',
 'top',
 'wanting',
 'absolutely',
 'adventure',
 'simply',
 'collection',
 'poor',
 'often',
 'third',
 'decided',
 'emotion',
 'history',
 'face',
 'shifter',
 'difficult',
 'called',
 'small',
 'humor',
 'setting',
 'hate',
 'certainly',
 'excellent',
 'four',
 'movie',
 'perhaps',
 'easily',
 'suspense',
 'event',
 'bed',
 'slow',
 'five',
 'talk',
 'missing',
 'spent',
 'hold',
 'dragon',
 'supposed',
 'stay',
 'complete',
 'list',
 'sentence',
 'learn',
 'play',
 'minute',
 'attraction',
 'break',
 'soul',
 'god',
 'continue',
 'killer',
 'across',
 'cute',
 'group',
 'fight',
 'marriage',
 'plan',
 'information',
 'tried',
 'based',
 'living',
 'finding',
 'beautiful',
 'question',
 'background',
 'week',
 'taking',
 'power',
 'pay',
 'kid',
 'kill',
 'mr',
 'married',
 'murder',
 'middle',
 'involved',
 'daughter',
 'realize',
 'surprise',
 'ex',
 'etc',
 'stuff',
 'son',
 'remember',
 'body',
 'predictable',
 'known',
 'alex',
 'seriously',
 'example',
 'extremely',
 'heat',
 'seen',
 'within',
 'behind',
 'level',
 'surprised',
 'content',
 'beyond',
 'magic',
 'amazing',
 'waiting',
 'desire',
 'mistake',
 'met',
 'lady',
 'form',
 'business',
 'became',
 'aspect',
 'trouble',
 'concept',
 'editor',
 'choice',
 'saying',
 'emotional',
 'immediately',
 'note',
 'close',
 'fit',
 'room',
 'force',
 'james',
 'view',
 'check',
 'loving',
 'early',
 'hunter',
 'science',
 'working',
 'building',
 'mark',
 'number',
 'christmas',
 'ability',
 'downloaded',
 'saw',
 'exactly',
 'due',
 'chemistry',
 'open',
 'original',
 'reviewed',
 'fell',
 'seeing',
 'important',
 'dead',
 'admit',
 'drawn',
 'taken',
 'picture',
 'connection',
 'despite',
 'annoying',
 'sequel',
 'share',
 'bring',
 'demon',
 'huge',
 'brought',
 'cannot',
 'willing',
 'wonder',
 'partner',
 'clear',
 'paid',
 'leaf',
 'becomes',
 'hoping',
 'fine',
 'somewhat',
 'special',
 'realistic',
 'forced',
 'ready',
 'simple',
 'return',
 'black',
 'space',
 'previous',
 'tension',
 'bdsm',
 'earth',
 'conflict',
 'present',
 'offer',
 'weak',
 'evil',
 'older',
 'expecting',
 'hurt',
 'quality',
 'taste',
 'please',
 'filled',
 'mostly',
 'trust',
 'paced',
 'bother',
 'hell',
 'unique',
 'build',
 'element',
 'using',
 'personal',
 'except',
 'fairy',
 'serial',
 'download',
 'piece',
 'christian',
 'basically',
 'spend',
 'control',
 'boyfriend',
 'mention',
 'telling',
 'passion',
 'decent',
 'anyway',
 'plus',
 'caught',
 'act',
 'graphic',
 'decides',
 'none',
 'serious',
 'mentioned',
 'rushed',
 'grammar',
 'published',
 'classic',
 'stupid',
 'strange',
 'fi',
 'described',
 'kate',
 'fairly',
 'paragraph',
 'horror',
 'super',
 'sci',
 'zombie',
 'flow',
 'date',
 'picked',
 'car',
 'worked',
 'crazy',
 'upon',
 'straight',
 'certain',
 'honest',
 'agree',
 'non',
 'menage',
 'lose',
 'drama',
 'writes',
 'exciting',
 'paper',
 'buying',
 'thriller',
 'gone',
 'fear',
 'sad',
 'police',
 'touch',
 'law',
 'blake',
 'step',
 'blog',
 'thank',
 'ghost',
 'single',
 'historical',
 'blood',
 'typo',
 'recommended',
 'game',
 'alien',
 'parent',
 'amount',
 'major',
 'knowing',
 'king',
 'honestly',
 'nature',
 'baby',
 'cat',
 'confusing',
 'jane',
 'available',
 'wrote',
 'master',
 'including',
 'personality',
 'copy',
 'thoroughly',
 'john',
 'purchase',
 'term',
 'neither',
 'club',
 'intriguing',
 'theme',
 'angel',
 'marry',
 'sound',
 'knight',
 'flat',
 'unless',
 'accept',
 'normally',
 'particularly',
 'promise',
 'purchased',
 'protagonist',
 're',
 'miss',
 'awesome',
 'thrown',
 'attempt',
 'whether',
 'talking',
 'hit',
 'added',
 'poorly',
 'worst',
 'meeting',
 'max',
 'wedding',
 'edition',
 'encounter',
 'held',
 'fully',
 'sample',
 'trilogy',
 'possible',
 'determined',
 'deep',
 'horrible',
 'decision',
 'pas',
 'basic',
 'moving',
 'struggle',
 'imagine',
 'ridiculous',
 'lord',
 'kelly',
 'typical',
 'near',
 'animal',
 'hooked',
 'suddenly',
 'effort',
 'fighting',
 'silly',
 'fantastic',
 'introduced',
 'joyfully',
 'modern',
 'cut',
 'otherwise',
 'reality',
 'focus',
 'comment',
 'wow',
 'stopped',
 'truth',
 'actual',
 'rape',
 'cause',
 'unbelievable',
 'escape',
 'develop',
 'jake',
 'th',
 'edge',
 'happily',
 'prequel',
 'voice',
 'interaction',
 'pace',
 'emma',
 'belief',
 'apparently',
 'leaving',
 'fire',
 'pleasure',
 'changed',
 'area',
 'lust',
 'worse',
 'odd',
 'conversation',
 'running',
 'american',
 'confused',
 'detective',
 'realized',
 'moved',
 'created',
 'hea',
 'period',
 'simon',
 'difference',
 'protect',
 'danger',
 'subject',
 'english',
 'plenty',
 'in',
 'yeah',
 'engaging',
 'article',
 'turning',
 'st',
 'watching',
 'disappointing',
 'jump',
 'west',
 'land',
 'missed',
 'city',
 'satisfying',
 'kaylee',
 'slave',
 'rich',
 'consider',
 'jack',
 'particular',
 'warning',
 'pain',
 'cop',
 'today',
 'door',
 'weird',
 'pull',
 'violence',
 'battle',
 'laugh',
 'decide',
 'conclusion',
 'lacking',
 'company',
 'looked',
 'crime',
 'red',
 'afraid',
 'late',
 'familiar',
 'wondering',
 'society',
 'journey',
 'formatting',
 'party',
 'reference',
 'skip',
 'nearly',
 'answer',
 'beauty',
 'location',
 'explanation',
 'apart',
 'ebook',
 'forever',
 'doubt',
 'throw',
 'falling',
 'literally',
 'draw',
 'race',
 'obviously',
 'eventually',
 'state',
 'ask',
 'included',
 'ship',
 'magazine',
 'grab',
 'appreciate',
 'imagination',
 'terrible',
 'bored',
 'normal',
 'news',
 'witch',
 'up',
 'us',
 'installment',
 'explicit',
 'owner',
 'inside',
 'final',
 'likable',
 'speak',
 'product',
 'keeping',
 'solid',
 'putting',
 'killed',
 'role',
 'cold',
 'killing',
 'starting',
 'bell',
 'similar',
 'brings',
 'trip',
 'holly',
 'adam',
 'towards',
 'outside',
 'wild',
 'heavy',
 'result',
 'low',
 'win',
 'happening',
 'team',
 'meant',
 'research',
 'college',
 'smart',
 'aside',
 'mysterious',
 'rough',
 'current',
 'member',
 'obvious',
 'verne',
 'section',
 'purpose',
 'ride',
 'lie',
 'claim',
 'realizes',
 'following',
 'nick',
 'barely',
 'attracted',
 'travel',
 'lived',
 'introduction',
 'bond',
 'physical',
 'cousin',
 'military',
 'teen',
 'detailed',
 'white',
 'letter',
 'complaint',
 'intense',
 'enjoying',
 'country',
 'received',
 'friendship',
 'explained',
 'nicely',
 'freebie',
 'cole',
 'rate',
 'usual',
 'format',
 'cry',
 'tired',
 'front',
 'spelling',
 'island',
 'walk',
 'awful',
 'survive',
 'henry',
 'continues',
 'constantly',
 'catch',
 'bar',
 'mistress',
 'incredibly',
 'watch',
 'dog',
 'victim',
 'cowboy',
 'younger',
 'powerful',
 'personally',
 'describe',
 'count',
 'ryan',
 'clearly',
 'sounded',
 'rachel',
 'memory',
 'robyn',
 'magical',
 'suggest',
 'handsome',
 'appears',
 'sleep',
 'whatever',
 'likeable',
 'michael',
 ...]

In [13]:
model.corpus_count

12000

In [14]:
model.wv.similar_by_word('good')

[('decent', 0.8629593849182129),
 ('great', 0.8376079797744751),
 ('nice', 0.8130007386207581),
 ('okay', 0.8099492192268372),
 ('satisfying', 0.8064167499542236),
 ('usually', 0.806216299533844),
 ('amazing', 0.8062124252319336),
 ('ok', 0.8055790662765503),
 ('alot', 0.8024327158927917),
 ('overall', 0.7962294816970825)]

In [15]:
# Applying avg_word2vec
import numpy as np

def avg_word2vec(doc):
  # Keep only known words
  sent = [word for word in doc if word in model.wv.index_to_key]

  # Handle empty document
  if len(sent) == 0:
    return np.zeros(model.vector_size)

  # Average word vectors
  return np.mean([model.wv[word] for word in sent], axis=0)

In [16]:
# Apply for the entire sentences
X=[]
for i in range(len(words)):
  X.append(avg_word2vec(words[i]))

In [17]:
X_new = np.array(X)

In [18]:
X_new.shape

(12000, 100)

In [ ]:
# Dependent Features
y = df['rating'].values
# If you already converted the ratings into binary values, then you don't need get_dummies() at all

In [20]:
y

array([1, 1, 1, ..., 1, 0, 1], shape=(12000,))

In [21]:
# Independent feature
# Converting vectors and dimensions into rows and columns
df = pd.DataFrame(X_new)

In [22]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.137631,0.301688,0.147085,0.064531,0.062885,-0.485979,0.127379,0.576724,-0.345531,-0.107846,...,0.355889,0.083428,-0.013309,0.160598,0.616677,0.328456,0.204552,-0.261392,-0.042007,-0.026641
1,-0.249870,0.169632,-0.162111,0.227867,-0.137714,-0.612084,0.563810,0.588352,-0.703625,-0.215723,...,0.587489,0.046775,-0.013559,-0.115468,0.642905,0.235853,0.310920,-0.235264,-0.035510,-0.092756
2,-0.180751,0.290766,-0.073855,0.072915,-0.026349,-0.541952,0.357874,0.619110,-0.410324,-0.038304,...,0.432618,0.067807,0.171322,0.037448,0.643425,0.230745,0.244863,-0.233626,-0.083096,0.073502
3,0.022321,0.252693,-0.211697,0.040665,0.050879,-0.512984,0.376378,0.683365,-0.269665,-0.108283,...,0.388726,-0.082476,0.206206,0.081191,0.596574,-0.029713,0.373120,-0.073340,-0.106151,0.165157
4,-0.175962,0.351993,0.317340,0.208738,-0.064674,-0.620663,0.347914,0.572066,-0.478042,-0.308298,...,0.657306,0.537261,0.131394,-0.253151,0.588312,0.292420,0.070885,-0.467900,0.280312,-0.007561

In [23]:
X=df

In [24]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.137631,0.301688,0.147085,0.064531,0.062885,-0.485979,0.127379,0.576724,-0.345531,-0.107846,...,0.355889,0.083428,-0.013309,0.160598,0.616677,0.328456,0.204552,-0.261392,-0.042007,-0.026641
1,-0.249870,0.169632,-0.162111,0.227867,-0.137714,-0.612084,0.563810,0.588352,-0.703625,-0.215723,...,0.587489,0.046775,-0.013559,-0.115468,0.642905,0.235853,0.310920,-0.235264,-0.035510,-0.092756
2,-0.180751,0.290766,-0.073855,0.072915,-0.026349,-0.541952,0.357874,0.619110,-0.410324,-0.038304,...,0.432618,0.067807,0.171322,0.037448,0.643425,0.230745,0.244863,-0.233626,-0.083096,0.073502
3,0.022321,0.252693,-0.211697,0.040665,0.050879,-0.512984,0.376378,0.683365,-0.269665,-0.108283,...,0.388726,-0.082476,0.206206,0.081191,0.596574,-0.029713,0.373120,-0.073340,-0.106151,0.165157
4,-0.175962,0.351993,0.317340,0.208738,-0.064674,-0.620663,0.347914,0.572066,-0.478042,-0.308298,...,0.657306,0.537261,0.131394,-0.253151,0.588312,0.292420,0.070885,-0.467900,0.280312,-0.007561

In [25]:
y

array([1, 1, 1, ..., 1, 0, 1], shape=(12000,))

In [26]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [28]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [29]:
y_pred=classifier.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.7679166666666667

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.68      0.58      0.63       801
           1       0.81      0.86      0.83      1599

    accuracy                           0.77      2400
   macro avg       0.74      0.72      0.73      2400
weighted avg       0.76      0.77      0.76      2400